/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_BOOTLOADER_METHODS_BOOTLOADER2_SOMEIP_STUB_ADAPTER_HPP_
#define V1_BOOTLOADER_METHODS_BOOTLOADER2_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/bootloader/methods/bootloader2Stub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace bootloader {
namespace methods {

template <typename _Stub = ::v1::bootloader::methods::bootloader2Stub, typename... _Stubs>
class bootloader2SomeIPStubAdapterInternal
    : public virtual bootloader2StubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< bootloader2SomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> bootloader2SomeIPStubAdapterHelper;

    ~bootloader2SomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        bootloader2SomeIPStubAdapterHelper::deinit();
    }

    void fireChangeEvent(const std::string &_appversion);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::bootloader::methods::bootloader2Stub,
        CommonAPI::Version
    > getbootloader2InterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::bootloader::methods::bootloader2Stub,
        std::tuple< >,
        std::tuple< bool, int32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::EmptyDeployment, CommonAPI::SomeIP::IntegerDeployment<int32_t>>
    > requestDownloadStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::bootloader::methods::bootloader2Stub,
        std::tuple< int32_t>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > requestDataStubDispatcher;
    
    bootloader2SomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        bootloader2SomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< bootloader2Stub>(_stub)),
        getbootloader2InterfaceVersionStubDispatcher(&bootloader2Stub::lockInterfaceVersionAttribute, &bootloader2Stub::getInterfaceVersion, false, true),
        requestDownloadStubDispatcher(
            &bootloader2Stub::requestDownload,
            false,
            _stub->hasElement(0),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)))
        
        ,
        requestDataStubDispatcher(
            &bootloader2Stub::requestData,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
    {
        bootloader2SomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x0) }, &requestDownloadStubDispatcher );
        bootloader2SomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &requestDataStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x1b58));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x2), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void bootloader2SomeIPStubAdapterInternal<_Stub, _Stubs...>::fireChangeEvent(const std::string &_appversion) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployed_appversion(_appversion, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x2),
            false,
             deployed_appversion 
    );
}


template <typename _Stub, typename... _Stubs>
void bootloader2SomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void bootloader2SomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::bootloader::methods::bootloader2Stub, typename... _Stubs>
class bootloader2SomeIPStubAdapter
    : public bootloader2SomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    bootloader2SomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          bootloader2SomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace methods
} // namespace bootloader
} // namespace v1

#endif // V1_BOOTLOADER_METHODS_bootloader2_SOMEIP_STUB_ADAPTER_HPP_
