/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_BOOTLOADER_METHODS_bootloader2_STUB_HPP_
#define V1_BOOTLOADER_METHODS_bootloader2_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/bootloader/methods/bootloader2.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace bootloader {
namespace methods {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service bootloader2. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class bootloader2StubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual bootloader2 {
 public:
    /**
    * Sends a broadcast event for change. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireChangeEvent(const std::string &_appversion) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for bootloader2.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class bootloader2StubRemoteEvent
{
public:
    virtual ~bootloader2StubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service bootloader2 to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class bootloader2Stub
    : public virtual CommonAPI::Stub<bootloader2StubAdapter, bootloader2StubRemoteEvent>
{
public:
    typedef std::function<void (bool _done, int32_t _fileSize)> requestDownloadReply_t;
    typedef std::function<void (std::string _data)> requestDataReply_t;

    virtual ~bootloader2Stub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 3);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method requestDownload.
    virtual void requestDownload(const std::shared_ptr<CommonAPI::ClientId> _client, requestDownloadReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method requestData.
    virtual void requestData(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _size, requestDataReply_t _reply) = 0;
    /// Sends a broadcast event for change.
    virtual void fireChangeEvent(const std::string &_appversion) {
        auto stubAdapter = CommonAPI::Stub<bootloader2StubAdapter, bootloader2StubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireChangeEvent(_appversion);
    }


    using CommonAPI::Stub<bootloader2StubAdapter, bootloader2StubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<bootloader2StubAdapter, bootloader2StubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<bootloader2StubAdapter, bootloader2StubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef bootloader2StubRemoteEvent RemoteEventType;
    typedef ::v1::bootloader::methods::bootloader2 StubInterface;
};

} // namespace methods
} // namespace bootloader
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_BOOTLOADER_METHODS_bootloader2_STUB_HPP_
