/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_BOOTLOADER_METHODS_bootloader2_STUB_DEFAULT_HPP_
#define V1_BOOTLOADER_METHODS_bootloader2_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/bootloader/methods/bootloader2Stub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace bootloader {
namespace methods {

/**
 * Provides a default implementation for bootloader2StubRemoteEvent and
 * bootloader2Stub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT bootloader2StubDefault
    : public virtual bootloader2Stub {
public:
    COMMONAPI_EXPORT bootloader2StubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(bootloader2::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT bootloader2StubRemoteEvent* initStubAdapter(const std::shared_ptr< bootloader2StubAdapter> &_adapter) {
        CommonAPI::Stub<bootloader2StubAdapter, bootloader2StubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void requestDownload(const std::shared_ptr<CommonAPI::ClientId> _client, requestDownloadReply_t _reply) {
        (void)_client;
        bool done = false;
        int32_t fileSize = 0;
        _reply(done, fileSize);
    }
    COMMONAPI_EXPORT virtual void requestData(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _size, requestDataReply_t _reply) {
        (void)_client;
        (void)_size;
        std::string data = "";
        _reply(data);
    }
    COMMONAPI_EXPORT virtual void fireChangeEvent(const std::string &_appversion) {
        bootloader2Stub::fireChangeEvent(_appversion);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual bootloader2StubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(bootloader2StubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        bootloader2StubDefault *defaultStub_;
    };
protected:
    bootloader2StubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace methods
} // namespace bootloader
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_BOOTLOADER_METHODS_bootloader2_STUB_DEFAULT
