/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/bootloader/methods/bootloader2SomeIPStubAdapter.hpp>
#include <v1/bootloader/methods/bootloader2.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace bootloader {
namespace methods {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createbootloader2SomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< bootloader2SomeIPStubAdapter<::v1::bootloader::methods::bootloader2Stub>>(_address, _connection, _stub);
}

void initializebootloader2SomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:bootloader.methods.bootloader2:v1_0:bootloader.methods.justSendHi",
         0x123a, 0x5678, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "bootloader.methods.bootloader2:v1_0",
        &createbootloader2SomeIPStubAdapter);
}

INITIALIZER(registerbootloader2SomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializebootloader2SomeIPStubAdapter);
}

} // namespace methods
} // namespace bootloader
} // namespace v1
